networks:
  sparkwork:
    driver: bridge
  traefik-global:
    external: true

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: leaderboard-api
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
      # Optional app-specific secrets/env here...
      # - ENVIRONMENT=production
    networks:
      - sparkwork
      - traefik-global
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leaderboard-api.rule=Host(`leaderboard-api.sparktobloom.com`)"
      - "traefik.http.routers.leaderboard-api.entrypoints=web"
      - "traefik.http.routers.leaderboard-api.priority=100"
      - "traefik.http.services.leaderboard-api.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik-global"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: leaderboard-bot
    restart: unless-stopped
    environment:
      LEADERBOARDBOT_TOKEN: ${LEADERBOARDBOT_TOKEN}
      API_BASE_URL: http://leaderboard-api:8000  # Use internal Docker DNS
      PYTHONUNBUFFERED: 1
    depends_on:
      - api
    volumes:
      - .:/app
    networks:
      - sparkwork